# Copyright 2023 ETH Zurich and University of Bologna.
# Solderpad Hardware License, Version 0.51, see LICENSE for details.
# SPDX-License-Identifier: SHL-0.51

# Author: Tim Fischer <fischeti@iis.ee.ethz.ch>

name: ci

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  svpkg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - name: Generate package
        run: |
          uv run --extra cli peakrdl raw-header tests/picobello.rdl --format svpkg --o svpkg.sv
      - name: Setup Verilator
        uses: veryl-lang/setup-verilator@v1
      - name: Lint SystemVerilog Package
        run: |
          verilator --lint-only svpkg.sv
