# Copyright 2023 ETH Zurich and University of Bologna.
# Solderpad Hardware License, Version 0.51, see LICENSE for details.
# SPDX-License-Identifier: SHL-0.51

# Author: Tim Fischer <fischeti@iis.ee.ethz.ch>

name: ci

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  svpkg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - name: Generate package
        run: |
          uv run --extra cli peakrdl raw-header --format svpkg tests/picobello.rdl -o addrmap.sv
      - name: Setup Verilator
        uses: veryl-lang/setup-verilator@v1
      - name: Lint SystemVerilog Package
        run: |
          verilator --lint-only addrmap.sv

  svh:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - name: Generate package
        run: |
          uv run --extra cli peakrdl raw-header --format svh tests/picobello.rdl -o addrmap.svh
      - name: Setup Verilator
        uses: veryl-lang/setup-verilator@v1
      - name: Lint SystemVerilog Package
        run: |
          verilator --lint-only tests/svh_pkg.sv -Itests

  c:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - name: Generate package
        run: |
          uv run --extra cli peakrdl raw-header --format c tests/picobello.rdl -o addrmap.h
      - name: Lint C Header
        run: |
          sudo apt-get install -y cppcheck
          cppcheck --enable=all --error-exitcode=1 addrmap.h
